[package]
name = "ntex"
version = "0.3.15"
authors = ["ntex contributors <team@ntex.rs>"]
description = "Framework for composable network services"
readme = "README.md"
keywords = ["ntex", "networking", "framework", "async", "futures"]
repository = "https://github.com/ntex-rs/ntex.git"
documentation = "https://docs.rs/ntex/"
categories = ["network-programming", "asynchronous",
              "web-programming::http-server",
              "web-programming::websocket"]
license = "MIT"
edition = "2018"

[package.metadata.docs.rs]
features = ["openssl", "rustls", "compress", "cookie"]

[lib]
name = "ntex"
path = "src/lib.rs"

[features]
default = []

# openssl
openssl = ["open-ssl", "tokio-openssl"]

# rustls support
rustls = ["rust-tls", "webpki", "webpki-roots", "tokio-rustls"]

# enable compressison support
compress = ["flate2", "brotli2"]

# enable cookie support
cookie = ["coo-kie", "coo-kie/percent-encode"]

# url support
url = ["url-pkg"]

[dependencies]
ntex-codec = "0.4.1"
ntex-rt = "0.2.2"
ntex-router = "0.4.2"
ntex-service = "0.1.8"
ntex-macros = "0.1.3"
ntex-util = "0.1.1"

base64 = "0.13"
bitflags = "1.2"
bytes = "1.0"
bytestring = { version = "1.0", features = ["serde"] }
derive_more = "0.99.13"
encoding_rs = "0.8"
futures-core = { version = "0.3.13", default-features = false, features = ["alloc"] }
futures-sink = { version = "0.3.13", default-features = false, features = ["alloc"] }
ahash = "0.7.2"
h2 = "0.3"
http = "0.2"
httparse = "1.3"
httpdate = "1.0"
log = "0.4"
mime = "0.3"
mio = "0.7.10"
num_cpus = "1.13"
nanorand = { version = "0.5", default-features = false, features = ["std", "wyrand"] }
percent-encoding = "2.1"
pin-project-lite = "0.2"
regex = { version = "1.4.5", default-features = false, features = ["std"] }
sha-1 = "0.9"
slab = "0.4"
serde = { version = "1.0", features=["derive"] }
serde_json = "1.0"
serde_urlencoded = "0.7"
socket2 = "0.4"
url-pkg = { version = "2.1", package = "url", optional = true }
coo-kie = { version = "0.15", package = "cookie", optional = true }
tokio = { version = "1", default-features = false, features = ["sync"] }

# openssl
open-ssl = { version="0.10", package = "openssl", optional = true }
tokio-openssl = { version = "0.6.1", optional = true }

# rustls
rust-tls = { version = "0.19", package = "rustls", optional = true }
webpki = { version = "0.21", optional = true }
webpki-roots = { version = "0.21", optional = true }
tokio-rustls = { version = "0.22", optional = true }

# compression
brotli2 = { version="0.3.2", optional = true }
flate2 = { version = "1.0.20", optional = true }

[dev-dependencies]
env_logger = "0.8"
rand = "0.8"
time = "0.2"
open-ssl = { version="0.10", package = "openssl" }
rust-tls = { version = "0.19", package="rustls", features = ["dangerous_configuration"]  }
webpki = "0.21"
futures = "0.3.13"
